mindbox-cloud/github-actions

azure-terraform-plan-and-commit/action.yml
yc-terraform-plan-and-commit/action.yml

Add azure composite

---

.github/workflows/frontend_ci.yml

https://github.com/mindbox-moscow/issues-devr/issues/1916

fix: adds style linters for frontend

---

.github/workflows/frontend_ci.yml

мотивация: писать в package.json версию релиза, чтобы совпадала версия пакета и в релиз в октопусе.

Kalyagin/f5/set release version to package.json

---

.github/workflows/frontend_ci.yml

Reverts mindbox-moscow/github-actions#30

Revert "Kalyagin/f5/set release version to package.json"

---

.github/workflows/frontend_ci.yml

Обновление версии в package.json
требует админских прав в репе для [frontend-gha](https://github.com/frontend-gha)
Будет замерджено 18.04

feat: запись версии релиза в package.json

---

.github/workflows/frontend_ci.yml

сделано в ожидании merge queue

ci: опициональный коммит в мастер свежей версии

---

.github/workflows/phrase_pull.yml
.github/workflows/phrase_sync.yml
localization/phrase-pull/action.yml
localization/translation-checker/action.yml

https://github.com/mindbox-moscow/issues-r2d2/issues/549

Разрешаем (при условии) кириллические комментарии в шарпе

---

.github/workflows/frontend_ci.yml

https://mindbox.youtrack.cloud/issue/F5-2119

feat: add optional docker release

---

.github/workflows/frontend_e2e.yml

https://github.com/mindbox-moscow/issues-devr/issues/1915

feat: adds checks for frontend e2e

---

notify-bump-packages/Dockerfile
notify-bump-packages/NotifyBumpPackages.sln
notify-bump-packages/NotifyBumpPackages/ActionInputs.cs
notify-bump-packages/NotifyBumpPackages/BumpPackagesNotifier.cs
notify-bump-packages/NotifyBumpPackages/ForgottenPullRequestDto.cs
notify-bump-packages/NotifyBumpPackages/MessageToGrafanaDto.cs
notify-bump-packages/NotifyBumpPackages/NotifyBumpPackages.csproj
notify-bump-packages/NotifyBumpPackages/Program.cs
notify-bump-packages/NotifyBumpPackagesTest/BumpPackagesNotifierTests.cs
notify-bump-packages/NotifyBumpPackagesTest/NotifyBumpPackagesTest.csproj
notify-bump-packages/README.md
notify-bump-packages/action.yml

https://github.com/mindbox-moscow/issues-framework/issues/596

add notify-bump-packages

---

generate-release-changelog/entrypoint.sh

Reverts mindbox-moscow/github-actions#62

Revert "feat: last commit hyperlink in changelog"

---

generate-release-changelog/entrypoint.sh

`%0A` не помог, пробую `<br/>`

fix: break line

---

.github/workflows/frontend_ci.yml

замерджим когда разрешится вопрос https://mindbox.slack.com/archives/C028EH2TP1C/p1659614963582639

feat: tag e2e image with release version

---

.github/workflows/frontend_ci.yml

Reverts mindbox-moscow/github-actions#70

Revert "feat: tag e2e image with release version"

---

kyverno-k8s-policies/action.yaml

https://github.com/mindbox-moscow/issues-platform/issues/107

[gha] add Kyverno checker composite

---

.github/workflows/frontend_deploy_hot_testing.yml

Для починки комментов со ссылкой на хоттестинг, применил готовый шаг

fix: comments in pr

---

.github/workflows/frontend_e2e.yml

https://mindbox.slack.com/archives/C09NTAM2M/p1670839515353419?thread_ts=1670423913.353429&cid=C09NTAM2M

fix: update node version to 14 for e2e

---

.github/workflows/frontend_ci.yml
.github/workflows/frontend_deploy_hot_testing.yml
.github/workflows/frontend_e2e.yml

- https://github.com/mindbox-moscow/issues-self-service/issues/1158

feat: remove input about s3 deploy

---

.github/workflows/frontend_e2e.yml

Добавил кэширование бинарников cypress на воркерах

fix: add cypress binary cache

---

azure-terraform-ci/action.yml
yc-terraform-ci/action.yml

Здесь тестил
https://github.com/mindbox-moscow/test-site/pull/52#issuecomment-1405121183
https://github.com/mindbox-moscow/test-site/pull/52#issuecomment-1405173555

[terraform-ci] Skip long plan comment

---

azure-terraform-ci/action.yml
yc-terraform-ci/action.yml

Тут пишут, что максимальный размер поменьше
https://github.com/robburger/terraform-pr-commenter/issues/6#issuecomment-826966670

[terraform-ci] Reduce max plan length

---

azure-terraform-ci/action.yml
yc-terraform-ci/action.yml

[terraform-ci] Truncate plan before comment

---

azure-terraform-ci/action.yml
yc-terraform-ci/action.yml

[terraform-ci] Fix shell

---

azure-terraform-ci/action.yml
yc-terraform-ci/action.yml

[azure-terraform-ci] Truncate with stdout

---

yc-terraform-ci/action.yml

[yc-terraform-ci] Truncate with stdout

---

push-to-aws-ecr-repository/action.yml
push-to-aws-ecr-repository/ecr-policy.json

https://github.com/mindbox-cloud/issues-platform/issues/826

[new] add push to aws ecr action

---

docker-push-to-all/action.yml
docker-push-to-all/ecr-policy.json

https://github.com/mindbox-cloud/issues-platform/issues/826

[docker-push-to-all] initial commit

---

push-to-aws-ecr-repository/action.yml

https://github.com/mindbox-cloud/issues-platform/issues/936

[push-to-aws-ecr-repository] Fix docker tag

---

.github/workflows/frontend_ci.yml
create-github-release/action.yml
helmfile-validate/action.yml

https://github.com/mindbox-cloud/issues-self-service/issues/1201
Pipelines нужна эта информация для соотношения билда с деплоем и вычисления метрики "Время выполнения пайплайна"
Также убираю self-hosted раннеры где они не нужны

Пушу информацию о релизе в pipelines

---

.github/workflows/frontend_ci.yml
.github/workflows/frontend_cleanup_testing.yml
.github/workflows/frontend_deploy_hot_testing.yml
.github/workflows/frontend_e2e.yml

Обновил версии стандартных экшенов перед переходом на ноду 18 во всех МКФ. Не должно зааффектить

fix: updates gh action versions

---

yc-terraform-ci/action.yml

Столкнулся с тем, что рендер длинного плана падает - видимо, трункейт не отрабатывает.
Воркфлоу сложный. Добавляю какой-то дебаг код.

trying to fix truncate

---

yc-terraform-ci/action.yml

Не влазиет в список аргументов.
https://github.com/mindbox-cloud/vault/actions/runs/4639377260/jobs/8212269030

truncate more

---

yc-terraform-ci/action.yml

trying to fix truncate plan

---

yc-terraform-ci/action.yml

Reverts mindbox-cloud/github-actions#172
Не помогло. Пойду подебажу как-нибудь ещё.

Revert "truncate plan to 30k"

---

yc-terraform-ci/action.yml

Reverts mindbox-cloud/github-actions#174
Не сработалё.

Revert "truncate plan to 8500 chars"

---

yc-terraform-ci/action.yml

Проверяю гипотезу, что env слишком длинный.

another try to fix truncate plan

---

yc-terraform-ci/action.yml

Забыл установить модуль и оказалось, что у github-actions нельзя указать рабочую директорию.

fix tf plan action

---

yc-terraform-ci/action.yml

another fix terraform plan action

---

yc-terraform-ci/action.yml

https://github.com/mindbox-cloud/yandex-cloud/actions/runs/4656953860/jobs/8241070151?pr=1555

try to fix tf plan action

---

generate-release-changelog/entrypoint.sh

https://github.com/mindbox-cloud/Nexus/actions/runs/4860423941/jobs/8666176326
не идет релиз, попытка понять причину

release problem inspection

---

.github/workflows/frontend_e2e.yml

Обновление версии контейнера, в котором запускается Cypress

update frontend e2e container image

---

.github/workflows/frontend_e2e.yml

https://github.com/mindbox-cloud/issues-platform/issues/1135

[frontend_e2e] Added dockerd max-upload param

---

.github/workflows/frontend_ci.yml

Добавила retry для push docker image
Тред: https://mindbox.slack.com/archives/C09NTAM2M/p1686211725469669

feat: add retry to push docker image

---

.github/workflows/frontend_ci.yml

Алерты вроде больше не падают, делаю чтобы ретрай работал у всех

feat: make the default value true

---

create-github-release/action.yml

Reverts mindbox-cloud/github-actions#210

Revert "[create-release-action] Clean grave accent symbol from changelogs"

---

azure-terraform-ci/action.yml

https://github.com/mindbox-cloud/issues-platform/issues/969
В azure падает с ошибкой из-за длинного плана. Фикшу аналогично яндексу

[azure-terraform-ci] Fix long plans

---

.github/workflows/frontend_deploy_hot_testing.yml

достаем из module-config.json  namespace потом пишем в GITHUB_ENV потом подставляем в hot-testing деплой

fix: read  mcf namespace

---

.github/workflows/frontend_ci.yml

fix: remove errors sentry from ci

---

terraform-ci-get-providers/action.yml
yc-terraform-ci/action.yml

https://github.com/mindbox-cloud/mailings-terraform/issues/89

[github] add action to store TF providers & update TF CI action

---

terraform-ci-get-providers/action.yml

https://mindbox.slack.com/archives/C028EH2TP1C/p1697710738761339

[actions] fix terraform init

---

yc-terraform-ci-v2/action.yml

Reverts mindbox-cloud/github-actions#244
https://mindbox.slack.com/archives/C044GQWDZA9/p1702993142563259

Revert "Add colors to yc-tf-ci action."

---

localization/translation-checker/action.yml

- https://github.com/mindbox-cloud/issues-self-service/issues/2435

Add new inputs to translation-checker

---

.github/workflows/frontend_deploy_hot_testing.yml

https://mindbox.slack.com/archives/C028EH2TP1C/p1708427683685959?thread_ts=1708423915.567749&cid=C028EH2TP1C

[workflows/frontend_deploy_hot_testing] fix check dns

---

.github/workflows/frontend_create_image.yml
.github/workflows/frontend_deploy_hot_testing.yml
.github/workflows/frontend_deploy_hot_testing_v2.yml
.github/workflows/frontend_e2e.yml
.github/workflows/frontend_e2e_v2.yml

- https://github.com/mindbox-cloud/issues-cdp/issues/5659

feat: create frontend_create_image.yml

---

.github/workflows/frontend_e2e.yml

https://mindbox.slack.com/archives/C050A9B9F/p1717054327932969?thread_ts=1717052676.382199&cid=C050A9B9F
https://mindbox.slack.com/archives/C09NTAM2M/p1717141048638259?thread_ts=1717082103.424209&cid=C09NTAM2M

change cypress image url

---

.github/workflows/frontend_e2e.yml

https://mindbox.slack.com/archives/C04GE6T8QQ4/p1717147051735309

fix: auth to cr.yandex

---

.github/workflows/frontend_ci.yml

https://mindbox.slack.com/archives/C050A9B9F/p1717064088571849?thread_ts=1717052676.382199&cid=C050A9B9F

chore: update frontend_ci.yml

---

.github/workflows/frontend_ci.yml

- https://github.com/mindbox-cloud/issues-self-service/issues/2894
- https://mindbox.slack.com/archives/C04K3M61927/p1719322762978489

feat: add forcePackageDownload to frontend-ci

---

terramate-generate/action.yml

https://mindbox.slack.com/archives/C028EH2TP1C/p1718041740271749

[gha] add terramate generate

---

notify-bump-packages/NotifyBumpPackages/ActionInputs.cs
notify-bump-packages/NotifyBumpPackages/BumpPackagesNotifier.cs
notify-bump-packages/NotifyBumpPackages/MessageToGrafanaDto.cs
notify-bump-packages/NotifyBumpPackages/Program.cs
notify-bump-packages/NotifyBumpPackagesTest/BumpPackagesNotifierTests.cs
notify-bump-packages/action.yml

This reverts commit fb78b06548cf6d67911ad4f8605048d4a8ab0271.

Revert "Fix NotifyBumpPackages - add integration uri argument (#292)"

---

.github/workflows/frontend_cleanup_testing.yml
.github/workflows/frontend_deploy_hot_testing.yml
.github/workflows/frontend_e2e.yml

- https://github.com/mindbox-cloud/issues-self-service/issues/3128
- Чтобы миграция на новый кластер проехала без breaking change нужно заменить старый токен на новый, заодно потом выпилю неиспользуемые переменные (остались после [выпила](https://github.com/mindbox-cloud/github-actions/commit/f90d7981e7b3c2e6dd9c11f8923c6ea719c66e10#diff-96ccc79a811b064a53db137bb54b7acc5b24cb217129f7fe15853e1cd1691f34) s3 деплоя)
План действий:
- вмержить этот ПР
- пройтись по всем фронтовым репам добавить прокидывание секрета (для ht, e2e, clenup)
- вмержить ПР с переводом ht в новый кластер: 
- https://github.com/mindbox-cloud/frontend-deploy/pull/460
- https://github.com/mindbox-cloud/github-actions/pull/294
- и в понедельник отдельный ПР с переводом e2e в новый кластер

Add k8 new token

---

.github/workflows/frontend_deploy_hot_testing.yml

- https://github.com/mindbox-cloud/issues-self-service/issues/3128

fix: dns check step

---

.github/workflows/frontend_cleanup_testing.yml
.github/workflows/frontend_e2e.yml

- https://github.com/mindbox-cloud/issues-self-service/issues/3128

fix: tests cleanup work dir

---

.github/workflows/frontend_deploy_hot_testing.yml
.github/workflows/frontend_e2e.yml

Ишью: [Issue #3314](https://github.com/mindbox-cloud/issues-platform/issues/3314)

deleting references dtln-kube-cdp-staging-01-a cluster

---

.github/workflows/frontend_ci.yml

fix: frontend_ci.yml

---

docker-push-to-all/action.yml

https://github.com/maestra-io/issues/issues/7

Add retries to "docker-push-to-all" action

---

docker-push-to-all/action.yml

https://github.com/maestra-io/issues/issues/7
- Добавил sourceRegistry, чтобы в CDP можно было прокидывать "cr.yandex/crpo9tj76o3c7pi8i72n" вместо обычного "local"
- Починил код создания репозиториев в AWS и вынес саму процедуру создания в отдельный шаг

Fix 'docker-push-to-all' action so it works with CPD

---

docker-push-to-all/action.yml

https://mindbox.loop.ru/mindbox/pl/jjgkojikiib8mbdooc7g8qjoby

feat(docker-push-to-all): Check that image actually was pushed

---

docker-push-to-all/action.yml

https://mindbox.loop.ru/mindbox/pl/jjgkojikiib8mbdooc7g8qjoby

fix(docker-push-to-all): Fail if image wasn't pushed

---

docker-push-to-all/action.yml

https://mindbox.loop.ru/mindbox/pl/e5617m6umbr7j8wk1bszx9u58e

Update docker-push-to-all (pull after push)

---

docker-push-to-all/action.yml

https://mindbox.loop.ru/mindbox/pl/a7d54jyrm7rn9rmeicciu4uphc

fix(docker-push-to-all): Fail if pull is not successful

---

.github/workflows/frontend_ci.yml

Fix config version for bundlemon

Fix config version for bundlemon

---

.github/workflows/frontend_ci.yml

Unused frontend steps cleanup

---

.github/workflows/frontend_ci.yml

Добавил поле, чтобы можно было настраивать на уровне конкретного фронта

fix: frontend_ci.yml input runs-on

---

.github/workflows/frontend_e2e.yml

fix: update in frontend_e2e.yml

---

.github/workflows/frontend_ci.yml

Публикуем пакет со сборкой в октопус, чтобы загружать её в с3

Release frontend with a package

---

.github/workflows/frontend_ci.yml

Reverts mindbox-cloud/github-actions#343

Revert "Add test coverage"
