mindbox-cloud/github-actions

- .github/workflows/phrase_sync.yml
Пушим и сразу пуллим, почти полная копия phrase_pull из фронтенда, только очищенная от всякого лишнего. Также часто подобный паттерн используется на беке, теперь копипастинг заменим на вызов этого воркфлоу. Фронтендеров тоже переведем на этот воркфлоу.
> Phrase sync workflow

- .github/workflows/frontend_e2e.yml
Запускаем джобы всегда(независимо от результатов предыдущих), если воркфлоу не заканселен.
При запуске проверяем зафейлился ли воркфлоу, если да, то убиваем джобу на старте.
> fix: fail e2e jobs if previous fails

- generate-release-changelog/entrypoint.sh
Хотим, чтобы Октопус уведомлял о выкладке в пулл реквесты микрофронтов. Сейчас такие нотификации подключены только для [DirectCrm](https://octopus.mindbox.ru/app#/Spaces-1/projects/directcrm/deployments/process/steps?actionId=d6a7671b-06c4-4ad9-9186-366c46b436f3)
Для работы шага [Notify Github](https://octopus.mindbox.ru/app#/Spaces-1/library/steptemplates/ActionTemplates-602) нужно чтобы в release notes октопуса была ссылка на последний коммит релиза
Вычисляем ссылку на последний коммит релиза через changelog
> feat: last commit hyperlink in changelog

- generate-release-changelog/entrypoint.sh
Возвращаю логику про last commit https://github.com/mindbox-moscow/github-actions/pull/62
Пофикшен баг, из-за которого терялось описание коммита
> fix: last commit

- helmfile-validate/action.yml
https://github.com/mindbox-cloud/issues-platform/issues/374
Добавляю простенький action для валидации helmfile.
- lint валидирует по жесткому
- template для того, чтобы подсмотреть результат рендеринга
Вызывается для каждого окружения, которое нужно отвалидировать. Авторизацию в registry не стал сюда заносить, чтобы не перегружать переменными. Для всех окружений вместе тоже не стал делать, - так смотреть результат неудобно, ну и вообще такого из коробки нет, нужно работать.
> Add helmfile-validate action

- .github/workflows/frontend_ci.yml
Хочу глобально уменьшить кол-во воркеров для юнит-тестов.
Можно, конечно, локально уменьшить в скрипте `npm run test`, но этот скрипт запускается так же локально перед пушем и локально хочется чтобы тесты гонялись быстрее. В CI есть проблема с 4 воркерами, поэтому ограничение нужно только в CI.
> fix(frontend_ci): reduces max number of workers for unit tests

- yc-terraform-ci/action.yml
Прочитал, что енвы имеют лимит длины в 31-32к.
> truncate plan to 30k

- yc-terraform-ci/action.yml
Проверка очередной гипотезы - где-то вычитал, что гитхаб позволяет ранить скрипты до 10Kb размером.
> truncate plan to 8500 chars

- .github/workflows/frontend_ci.yml
Поправила таймауты на основе 3-ёх успешных пайплайнов:
**"Push release docker image to registry with retry"** - 16s, 13s, 13s = 20s
**"Push e2e docker image to registry with retry"** - 56s, 32s, 46s = 1m
Подняла общий таймаут для релиза с 20 до 25 минут на глаз на основе неуспешных 3-ёх пайплайнов с шагом релиза **"Push e2e docker image to registry with retry"** - 7m 44s, 5m 11s, 10m 15s -  5 минут будет доп. запас
> fix: fix timeouts for step retry

- .github/workflows/frontend_ci.yml
из тикета в саппорте https://mindbox.slack.com/archives/C03PMP0UCBZ/p1688389982417399
Решили что будет норм добавить переменные таймауты для джоб,  что-бы мкф могли подстраивать под себя
> fix: add variable for jobs timeout

- .github/workflows/frontend_e2e.yml
- сломался пакет @cypress/grep из-за него не могут стартовать тесты frontend-staff в core-v2
- Временно удаляем переменную,  пока [grepFilters](https://github.com/cypress-io/cypress/issues/27216) не починят
> fix: remove grep filters

- create-github-release/action.yml
Обкатал для scenarios-runtime. [GHA](https://github.com/mindbox-cloud/scenarios-runtime/blob/main/.github/workflows/release.yml#L80), [релиз в Octopus
](https://octopus.mindbox.ru/app#/Spaces-1/projects/scenarios-runtime/deployments/releases/1.0.2699)<img width="1792" alt="image" src="https://github.com/mindbox-cloud/github-actions/assets/50952031/a1626330-905c-4165-ab55-8222c03f3314">
> Add "first built on" to release notes

- ensure-bump/action.yaml
Когда делал ПР в либу локализации (там используется этот экшон) - увидел предупреждение, решил поправить
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Fix set-output

- .github/workflows/frontend_ci.yml
- .github/workflows/frontend_deploy_hot_testing.yml
- .github/workflows/frontend_e2e.yml
- .github/workflows/frontend_library_ci.yml
Фиксируем версию ноды таким образом, чтобы у нас не стрелял иногда npm 10, переход надо делать явным.
Подарок в последней минорке [ноды](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.19.0)
> fix: node version with npm 9+

- notify-bump-packages/NotifyBumpPackages/ActionInputs.cs
- notify-bump-packages/NotifyBumpPackages/BumpPackagesNotifier.cs
- notify-bump-packages/NotifyBumpPackages/MessageToGrafanaDto.cs
- notify-bump-packages/NotifyBumpPackages/Program.cs
- notify-bump-packages/NotifyBumpPackagesTest/BumpPackagesNotifierTests.cs
- notify-bump-packages/action.yml
[Задача](https://github.com/mindbox-cloud/issues-mailings/issues/2490)
[Тред с FWK](https://mindbox.loop.ru/mindbox/pl/z1rnnk4n6bfrfkh4b57etij44a)
Хотим себе в трайб такой экшн, но он не работает из-за переезда на луп - подправил логику так, чтобы все, кто хочет, могли себе это настроить и другим не мешать. Теперь надо будет вместо имени команды писать url интеграции в графане.
[Ранбук](https://www.notion.so/mindbox/1d41e12423994dabbabd4e452cc36c0f#9ef64247f66049ada41796b72f4227ba) подправлю.
Локально протестил - всё работает, [вот пруф из графаны](https://mindbox.grafana.net/a/grafana-oncall-app/alert-groups/IZUFQ2CQV6WWZ?perpage=25&search=Bump&start=1&started_at=now-30d_now).
> Fix NotifyBumpPackages - add integration uri argument

- yc-terraform-ci/action.yml
[Тут](https://github.com/mindbox-cloud/github-actions/commit/17236e6be36f1fcbb528d0967b6384e066522b9c#diff-04998d12dff0b4d37917bd0b5dcc95623a4f060e3a2843d6ab4ab357afb4519c) обновили до v4 экшен сохранения артифактов, из-за этого видимо v3 версия экшена загрузки артифакта не видит его
https://mindbox.loop.ru/mindbox/pl/mda5x1pzepf7trnaj5hjihk6yy
> Bump actions/download-artifact

- yc-terraform-ci/action.yml
Если в экшене выставить переменную `tfUseLocalSetup: 'false'`, то экшен упадёт на шаге установки `fs` модуля
```
- name: "Install fs module"
run: npm install fs
shell: bash
```
Потому что скипнется шаг установки npm
``` 
- name: "Setup Node & NPM"
uses: actions/setup-node@v3
if: ${{ inputs.tfUseLocalSetup == 'true' }}
with:
node-version: 18
```
В итоге экшен упадёт
```
Run npm install fs
npm install fs
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
/runner/_work/_temp/2042b2b3-b954-4333-9b79-28049e870041.sh: line 1: npm: command not found
```
Хочу убрать ` if: ${{ inputs.tfUseLocalSetup == 'true' }}` из шага, чтобы всегда устанавливать npm
> [github-actions] Always install node and npm package. This need for "Comment plan" step

- .github/workflows/frontend_ci.yml
Временно делаем двойную сборку фронта, поэтому нужно в 2 раза больше памяти. Из-за этого в некоторых МКФ падает сборка. Пока не мигрируем на новый вариант сборки, нужно временно увеличить память для ноды.
https://tracker.yandex.ru/FRONTEND-4
> Increase frontend node memory limit

- terraform-ci-dns/action.yml
[loop](https://mindbox.loop.ru/mindbox/pl/9rm5uegpo3n1jr8ske1c789h6y)
Сейчас при слишком большом выводе terraform-plan ci падает. 
Замечено, что весь вывод почему-то оказывается в строках, начинающихся с `::debug::`. Вроде как в yandex-terraform-ci, на основании кт сделано, такой проблемы нет. Я просто вырезаю эти строки и забиваю на поиск более красивого решения
> [terraform-ci-dns] fix comment

- .github/workflows/frontend_ci.yml
- .github/workflows/frontend_e2e.yml
Добавил флоу для работы с Playwright
Cypress пока не трогаем, он запускается безусловно
1. Добавил создание образа с отдельным тэгом при релизе
2. Прогон тестов конструктора на playwright в ПР коры, тут же добавил нужные env'ы
3. Прогон тестов на playwright в ПР, если e2e_runner передан как playwright. При этом cypress пока все равно запускается тоже
> Add playwright workflow

- .github/workflows/frontend_e2e.yml
Добавил возможность запускать e2e для cypress/playwright как раздельно, так и вместе
> Split cypress and playwright tasks
